server:
  port: 8081

jwt:
  issuer: jara
  subject: auth
  expires-time: 3600
  secret: my-secret

#
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/db_example
    username: root
    password: root






#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db_example?useSSL=false
#    username: root
#    password: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: mysql
#    show-sql: true
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl







#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    properties:
#      hibernate:
#        storage_engine: innodb
#        format_sql: true
#        use_sql_comments: true
#    hibernate:
#      ddl-auto: none
#    open-in-view: false
#    show_sql: true
#
#  logging.level:
#    org.hibernate.SQL: debug