server:
  port: 8084


auth:
  url: http://127.0.0.1:8083/api/users/me


#spring:
#  r2dbc:
#    url: r2dbc:mysql://study-database.cvu8f5neikqk.ap-northeast-2.rds.amazonaws.com:3306/study_db
#    username: root
#    password: test1234

spring:
  datasource:
    url: jdbc:mysql://study-database.cvu8f5neikqk.ap-northeast-2.rds.amazonaws.com:3306/study_db?serverTimezone=UTC
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  aws:
    credentials:
      access-key: AKIATAY546U2JVEJFUGD
      secret-key: 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
    s3:
      bucket-name: ns-market
      region: ap-northeast-2
      folder-name: board
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  r2dbc:
#    url: r2dbc:mysql://study-database.cvu8f5neikqk.ap-northeast-2.rds.amazonaws.com:3306/study_db
#    username: root
#    password: test1234

upload:
  path: ./uploads/